export const CATEGORIES = [
  { key: "FruitsVeg", name: "Fruits and Vegetables" },
  { key: "Meat", name: "Meat" },
  { key: "Seafood", name: "Fish and Seafood" },
  { key: "DairyEggs", name: "Dairy and Eggs" },
  { key: "Bakery", name: "Bakery and Pastry" },
  { key: "Snacks", name: "Snacks and Confectionery" },
  { key: "BeveragesNonAlc", name: "Non-Alcoholic Beverages" },
  { key: "BeveragesAlc", name: "Alcoholic Beverages" },
  { key: "Frozen", name: "Frozen Foods" },
  { key: "PreparedMeals", name: "Prepared Meals" },
  { key: "GroceriesOther", name: "Other Groceries" },
  { key: "Restaurants", name: "Restaurants and Cafes" },
  { key: "UtilitiesSupplies", name: "Utilities and Supplies" },
  { key: "Pharmacy", name: "Pharmacy and Medicines" },
  { key: "Hygiene", name: "Hygiene and Personal Care" },
  { key: "Cosmetics", name: "Cosmetics and Beauty" },
  { key: "Clothing", name: "Clothing and Footwear" },
  { key: "Jewelry", name: "Jewelry and Accessories" },
  { key: "Electronics", name: "Electronics and Gadgets" },
  { key: "Transport", name: "Transportation" },
  { key: "Entertainment", name: "Entertainment" },
  { key: "Education", name: "Education and Courses" },
  { key: "Subscriptions", name: "Subscriptions and Memberships" },
  { key: "Misc", name: "Miscellaneous" },
];
